#!/bin/bash

die() {
    echo "$@" >&2
    exit 1
}

init() {

    if [ -f .env ]; then
        echo "Load ENV"
        # shellcheck disable=SC1091
        . .env
    fi

    php=${php:-ea-php73}

    if [ -f composer.json ]; then

        echo "Dealing with composer"

        # Install composer
        echo "instaling composer"
        curl -s http://getcomposer.org/installer | "$php" >/dev/null
        composer="$php composer.phar"

        # Install or update packages specified lock file
        $composer --no-ansi install

    fi


    if [ -f package.json ]; then
        echo "Dealing with npm"
        npm install
    fi

    if [ -f bower.json ]; then
        echo "Dealing with bower"
        bower install
    fi

    if [ -f gulpfile.js ]; then
        echo "Dealing with gulp"
        gulp
    fi

    if [[ -f config/phinx.php ]] ; then
        echo "Dealing with phinx"
        "$php" vendor/bin/phinx -c./config/phinx.php migrate
    fi

    if [[ -f vendor/bin/bootstrap-css ]] ; then
        echo "Compiling CSS"
        "$php" vendor/bin/bootstrap-css
    fi

    if [[ -x bin/deploy ]] ; then
        echo "Deploy script"
        bin/deploy
    fi
}

deploy() {
    local path=$1 branch=$2
    echo "deploying $branch to $path ..."
    GIT_WORK_TREE=${path} git checkout -f "$branch"
    echo "Initialize application"
    pushd "${path}" || exit 1
    init
    popd || exit 1
}

while read -r _ _ ref; do
    case $ref in
    refs/heads/master) deploy ../production master;;
    refs/heads/develop) deploy ../staging develop;;
    esac
done


