#!/usr/bin/env bash

die() {
    echo "$@" >&2
    exit 1
}

init() {
    local env=$1

    if [ -f .env ]; then
        echo "Loading .env file"
        # shellcheck disable=SC1091
        source .env
    fi

    [ -f Makefile ] && make ENV="$env"
}

deploy() {
    local branch=$1
    local path=$2
    local env=$3

    printf "deploying %s to %s with env %s...\n" "$branch" "$path" "$env"
    GIT_WORK_TREE=${path} git checkout -f "$branch"

    printf "initialize application\n"
    pushd "$path" || die "cannot switch to $path"
    init "$env"
    popd || die "something wrong with paths"
}

while read -r _ _ ref; do
    case $ref in
    refs/heads/master) deploy master ../production production;;
    refs/heads/develop) deploy develop ../staging staging;;
    esac
done
